### ISSUE TITLE
Quickstart does not register succesful connections

### ISSUE THREAD

**Issue by souredoutlook** [launchdarkly/hello-node-server#13]
I am following the quickstart guide that uses the code found in this repo 

https://app.launchdarkly.com/default/production/get-started/connect-an-sdk

When I run the application I see successful messages in my console:

```
info: [LaunchDarkly] Initializing stream processor to receive feature flag updates
info: [LaunchDarkly] Opened LaunchDarkly stream connection
*** SDK successfully initialized!

*** Feature flag 'test-flag' is false for this context
```

I even flipped the flag in the UI to see if I could influence the output and it works as expected.

```
info: [LaunchDarkly] Initializing stream processor to receive feature flag updates
info: [LaunchDarkly] Opened LaunchDarkly stream connection
*** SDK successfully initialized!

*** Feature flag 'test-flag' is true for this context
```

But the quickstart onboarding flow does not seem to acknowledge any of the above.

**Comment by kinyoklion** [comment]
Hello @souredoutlook,

Thank you for the issue. I see that the `connect-an-sdk` page is out of date (written for the previous implementation of the SDK 7.x and lower). I will see about getting that updated.

Thank you,
Ryan

**Comment by souredoutlook** [comment]
hey @kinyoklion I can see that there are some material differences between the content and that page and the most recent version of this repo, however using the code and package versions from this repo do not result in a successful quick start: 
<img width="907" alt="image" src="https://github.com/launchdarkly/hello-node-server/assets/76002357/d2bb4072-e7e7-4de3-a46b-11834934801e">

**Comment by souredoutlook** [comment]
That being said - the SDK and example does work as expected so I suppose you can close this issue as the problem seems to reside with the LaunchDarkly application itself.

**Comment by kinyoklion** [comment]
Can you verify, by adding a log or using the debugger, that the code is reaching here:
```
    ldClient.flush(function () {
     // Do you reach this point? Indicating a flush is complete.
      ldClient.close();
    });
```

If you do, then remove the close and see if there is any difference, if so, then let me know.

Otherwise you probably need to file a support ticket. 

Thank you,
Ryan

**Comment by souredoutlook** [comment]
Hi @kinyoklion the code is reaching there and I do see the contexts in LD - I think it's just the onboarding tool that is not working as expected here - not your example. 

👍
